A1:
  _target_: rm_marl.agent.RewardMachineLearningAgent
  algo_kws:
    action_space: 
      _target_: builtins.getattr
      _args_:
        - ${envs.local.env1}
        - action_space
A2:
  _target_: rm_marl.agent.RewardMachineLearningAgent
  algo_kws:
    action_space: 
      _target_: builtins.getattr
      _args_:
        - ${envs.local.env2}
        - action_space
A3:
  _target_: rm_marl.agent.RewardMachineLearningAgent
  algo_kws:
    action_space: 
      _target_: builtins.getattr
      _args_:
        - ${envs.local.env3}
        - action_space
