import random
import abc
import gym
import numpy as np


class LabelTampering(gym.Wrapper):
    """
    Environment wrapper to allow for labeling function output tampering.

    This wrapper defines a common interface for tampering with the labeling function output of the underlying env.
    Subclasses only need to implement the _tamper_events() method, which should contain the actual tampering logic.
    That method is invoked for every event generated by the labeling function of the underlying environment.
    """

    def __init__(self, env):

        assert hasattr(env, 'get_all_labels'), "Wrapped env must be wrapped by LabelingFunctionWrapper or implement get_all_labels()"

        super().__init__(env)

        self._all_events = env.get_all_labels()
        self._n_tamperings = 0
        self._n_candidates = 0

    @abc.abstractmethod
    def _tamper_events(self, events):
        """
        Labeling function output tampering logic.

        This method must be implemented by concrete subclasses to implement the actual tampering logic. Note that
        a labeling function tamperer is not required to tamper with every event: based on the case at hand, the output
        of this method can be the same exact events  that were received as input.

        :param events: The LF output to be tampered with
        :return: The tampered event string
        """

        raise NotImplementedError('LF tamperers must inherit from this class and override this method')

    @abc.abstractmethod
    def _is_tamperable(self, events):
        """
        Logic for choosing potential candidate LF outputs that could be tampered with

        This method must be implemented by concrete subclasses to filter between the LF outputs that could be subject
        to the desired tampering logic. For instance, a blinding-style tamperer can only consider as candidates the LF
        outputs that contain at least one event.

        Note that this method returning True *does not* mean that a given LF output will actually be modified: it simply
        means that it is a valid candidate that could, in theory, be subject to the tampering logic. Choosing whether
        the LF output will actually be tampered with is left as a responsibility of the _tamper_events() method.

        :param events: The LF output to be examined
        :return: True, if the given LF output is a valid tampering cadidate
        """

        raise NotImplementedError('LF tamperers must inherit from this class and override this method')

    def step(self, action):
        """
        Step the environment while applying the labeling function tampering procedure

        :param action: The action to be taken by the agent
        :return: obs, reward, terminated, truncarted, info as by Gym APIs
        """

        obs, reward, terminated, truncated, info = self.env.step(action)

        # Apply the tampering logic
        true_events = info['labels']

        if self._is_tamperable(true_events):

            self._n_candidates += 1

            tampered_events = self._tamper_events(true_events)

            if tampered_events != true_events:
                self._n_tamperings += 1

            # Substitute the labels returned in step() output
            info['labels'] = tampered_events

        return obs, reward, terminated, truncated, info

    @property
    def n_tamperings(self):
        """
        Returns the number of times this tamperer has modified the labelling function output so far.
        Note that the reported value IS NOT reset to zero when an episode terminates.

        :return: Number of labelling function output tamperings so far
        """
        return self._n_tamperings

    @property
    def n_candidates(self):
        """
        Returns the number of times the tamperer has seen a potentially tamperable LF output so far.
        Note that the reported value IS NOT reset to zero when an episode terminates.

        :return: Number of temperable LF outputs observed so far
        """

        return self._n_candidates

    @property
    def tampering_rate(self):
        """
        Returns the overall tampering rate so far, ie: the ratio of the number of tampered LF outputs and the number of
        potentially tamperable LF outputs so far
        """

        if self.n_candidates == 0:
            return np.nan

        return self.n_tamperings / self.n_candidates


class RandomHallucinationNoise(LabelTampering):
    """
    Labeling function tamperer that randomly alters abstract observation with a given probability.

    This tamperer adopts the following noise model:

     - every labelling function output might be subject to noise;
     - every labelling function output tampering might consist of the removal (blinding) or substitution of any event
       in the original event string
    """

    def __init__(self, env, noise_quantity, *, seed=None):

        super().__init__(env)

        assert 0.0 < noise_quantity < 1.0, "Noise quantity must be in range [0, 1]"
        self._noise_quantity = noise_quantity
        self._seed = seed
        self._random = random.Random(self._seed)

    def _is_tamperable(self, events):

        return len(events) > 0

    def _tamper_events(self, events):

        if self._random.random() < self._noise_quantity:

            # Chose a random position in the event string to tamper
            target_index = self._random.randint(0, len(events) - 1)

            # Chose a random substitute event
            substitute = self._random.choice(self._all_events)

            # If the chosen substitute is already present in the true events, simply remove the original one
            if substitute in events:
                del events[target_index]

            # If not, carry out the substitution
            else:
                events[target_index] = substitute

        return events


class RandomBlindingNoise(LabelTampering):

    def __init__(self, env, noise_quantity, *, seed=None):

        super().__init__(env)

        assert 0.0 < noise_quantity < 1.0, "Noise quantity must be in range [0, 1]"
        self._noise_quantity = noise_quantity
        self._seed = seed
        self._random = random.Random(self._seed)

    def _is_tamperable(self, events):

        return len(events) > 0

    def _tamper_events(self, events):

        # Determine if this labelling function output will be tampered
        if self._random.random() < self._noise_quantity:

            # Chose a random position in the event string to tamper
            target_index = self._random.randint(0, len(events))

            # Remove the event string as a whole (compound tampering)
            if target_index == len(events):
                return []
            # Remove the event at the specified index
            else:
                tampered_events = events[:target_index] + events[target_index + 1:]
                return tampered_events

        else:

            return events
