# @package _global_

algo:
  lr:
    best_value: 0.0006829733920627158
model:
  fcnet_hiddens:
    best_value: [32]
  fcnet_activations:
    best_value: "tanh"
  lstm_cell_size:
    best_value: 8
ppo:
  mini_batch_size_per_learner:
    best_value: 500
  clip_param:
    best_value: 0.2
  vf_clip_param:
    best_value: 8.218233187442518
  kl_target:
    best_value: 0.23357623600710184
  kl_coeff:
    best_value: 0.54157596324785
  num_sgd_iter:
    best_value: 25
  lambda_:
    best_value: 0.9918831836286752
  vf_loss_coeff:
    best_value: 0.7018824317182417
  entropy_coeff:
    best_value: 0.0351937552858181
