edge_cost: 2
n_phi_cost: 1
ex_penalty_multiplier: 8
additional_ex_penalty_multipler: 2
min_penalty: 4
cross_entropy_threshold: 0.6

base_dir: null

# Whether we should rebalance classes during RM learning
rebalance_classes: True

new_inc_examples: True

# Wherther we should replay experiences; generally useful but can require a lot of RAM
replay_experience: False

max_container_size: null 

# Note: Do not change. This value is filled in by run config
use_old_rm_learner: null