_target_: rm_marl.agent.RewardMachineAgent
agent_id: ${..config.agent_id}
rm: 
  _target_: rm_marl.reward_machine.RewardMachine.load_from_file
  file: ${...config.rm_file}
algo_kws:
  action_space: 
    _target_: builtins.getattr
    _args_:
      - ${.....env}
      - action_space