stop_iters: 500
seed: 123

num_agents: 1
name: "Custom-PPO"

num_env_runners: 1

recurrent: False
use_perfect_rm: True
# Bug: use_rs: False doesn't get launched; set shaping reward = before returing for now
use_rs: True
rs_discount: 0.99


# TODO: add checkpoint

should_tune: True

tune_config:
  num_samples: 1
  verbose: 2
  checkpoint_freq: 0
  checkpoint_at_end: False
  # TODO: put scheduler method as part of hydra config
  scheduler:
    metric: "env_runners/original_episode_return_mean"
    mode: "max"
    min_grace_period: 15

wandb:
  project: "Prob-IRM"
  run_name: "run"
  key: null


# How often should we render episode videos and heatmap
render_freq: 10