# @package _global_

algo:
  lr:
    best_value: 0.0004578127680285286
model:
  fcnet_hiddens:
    best_value: [8, 8]
  fcnet_activation:
    best_value: "elu"
ppo:
  mini_batch_size_per_learner:
    best_value: 128
  clip_param:
    best_value: 0.2
  vf_clip_param:
    best_value: 17.58088446015339
  kl_target:
    best_value: 0.004801365262525935
  kl_coeff:
    best_value: 0.3305709305540696
  num_sgd_iter:
    best_value: 3
  lambda_:
    best_value: 0.9102573208710695
  vf_loss_coeff:
    best_value: 0.9919536698878115
  entropy_coeff:
    best_value: 0.05461576801837325
