# @package _global_

algo:
  lr:
    best_value: 0.0002304631701668832
model:
  fcnet_hiddens:
    best_value: [32, 32]
  fcnet_activation:
    best_value: "tanh"
ppo:
  mini_batch_size_per_learner:
    best_value: 64
  clip_param:
    best_value: 0.2
  vf_clip_param:
    best_value: 4.639327433791415
  kl_target:
    best_value: 0.010320099158613536
  kl_coeff:
    best_value: 0.619723541800079
  num_sgd_iter:
    best_value: 9
  lambda_:
    best_value: 0.9494316202196903
  vf_loss_coeff:
    best_value: 0.5876863303899578
  entropy_coeff:
    best_value: 0.03149664458906861
