defaults:
  - ../base@_here_
  - agent_type@agent: rm_learning

config:
  agent_id: ???
  random_label_config: ???
  rm_file: ???

env:
  _target_: rm_marl.utils.gym.wrap_env
  _args_:
    - _target_: gym.make
      id: ${....config.env_id}
      render_mode: ${....config.env_render_mode}
      file: ${....config.env_file}
    -
      - cls: 
          _target_: rm_marl.utils.imports.import_cls
          path: rm_marl.envs.wrappers.SingleAgentEnvWrapper
        args: 
          - ${......config.agent_id}
      - cls: 
          _target_: rm_marl.utils.imports.import_cls
          path: rm_marl.envs.buttons.ButtonsLabelingFunctionWrapper
      - cls: 
          _target_: rm_marl.utils.imports.import_cls
          path: rm_marl.envs.wrappers.RandomLabelingFunctionWrapper
        args: 
          - ${......config.random_label_config}
      - cls: 
          _target_: rm_marl.utils.imports.import_cls
          path: rm_marl.envs.wrappers.RewardMachineWrapper
        args: 
          - _target_: rm_marl.reward_machine.RewardMachine.load_from_file
            file: ${.......config.rm_file}
        kwargs:
          label_mode: 
            _target_: builtins.getattr
            _args_: 
              - _target_: builtins.getattr
                _args_: 
                 - _target_: rm_marl.utils.imports.import_cls
                   path: rm_marl.envs.wrappers.RewardMachineWrapper
                 - LabelMode
              - ${........config.label_mode}
      - cls: 
          _target_: rm_marl.utils.imports.import_cls
          path: rm_marl.envs.wrappers.RecordEpisodeStatistics
