defaults:
  - base

config:
  agent_id: A1
  rm_file: data/rendezvous/rm_agent_1.txt
  onestate_rm_file: data/rendezvous/onestate_rm_agent_1.txt
  random_label_config:
    r: 
      _target_: rm_marl.envs.wrappers.RandomLabelingConfig
      proba: 0.3
      condition:
        _target_: builtins.getattr
        _args_:
          - _target_: rm_marl.utils.imports.import_cls
            path: rm_marl.envs.rendezvous.RendezVousRandomLabelingFunctionWrapper
          - rdv_unsatisfied_AND_A1_rdv
      env_update:
        _target_: builtins.getattr
        _args_:
          - _target_: rm_marl.utils.imports.import_cls
            path: rm_marl.envs.rendezvous.RendezVousEnv
          - move_A2_to_rdv