config:
  rm_file: ???
  env: ???

agent:
  _target_: rm_marl.agent.RewardMachineAgent
  rm: 
    _target_: rm_marl.reward_machine.RewardMachine.load_from_file
    file: ${...config.rm_file}
  algo_kws:
    action_space: 
      _target_: builtins.getattr
      _args_:
        - ${envs.local.${.....config.env}}
        - action_space