training: True
total_episodes: 500
log_freq: 1
log_dir: logs
testing_freq: 250
greedy: True
synchronize: False
counterfactual_update: False
recording_freq: 250
no_display: False
seed: 123
name: ??? # should make ???
extra_debug_information: False

# TODO: move somewhere else
edge_cost: 1
n_phi_cost: 1
ex_penalty_multiplier: 2
